### PR TITLE
fix: update reference to supabase official repo

### PR DESCRIPTION
**Pull request by J0**
Version is unchanged. Supabase has decided to move Python from `supabase-community` to the official repo

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by J0** [comment]
conda-forge-admin please rerender

**Comment by J0** [comment]
@conda-forge-admin please rerender

**Review by timkpaine — CHANGES_REQUESTED** [review]
build number

**Comment by J0** [comment]
Sorry, initially wasn't sure where to find it so took a while. Thanks for jumping in so quickly!

**Pull request merged**
